### ISSUE TITLE
faulty port definition

### ISSUE THREAD

**Issue by Nemesis77swe** [asifbacchus/fail2banUFW#1]
hi!

in ufw-probe.conf you set;

port = any

but it should be;

port = 0:65535

**Comment by asifbacchus** [comment]
I haven't been having any problems with 'any' in my configuration... has there been a change in a recent update and you find it no longer works? In previous versions `0:65535` was the same as `any` because the former literally would be 'any' port. If this has changed, I'm happy to update the repo... been meaning to see if any updates were required anyways.

**Comment by Nemesis77swe** [comment]
hi!

this is what the log said:

[2608]: ERROR   7f9281692660 -- stderr: "iptables v1.8.4 (legacy): invalid port/service `all' specified"

and when I changed the conf to 0:65535 it worked, so I assume something have changed..

**Comment by asifbacchus** [comment]
I will check into this with F2B hopefully this weekend and then update the repo.

Thanks for pointing this out! :-)

**Comment by asifbacchus** [comment]
Seems you are correct! The official sample configurations now use the `0:65535` instead of `any`. I'm gonna take a quick review of the repo since I haven't checked in on it for a while. I'll include this fix with any other minor ones I find.

Thanks again :-)

**Comment by asifbacchus** [comment]
closed by fe5a9cd
